; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=4
    -D USER_SETUP_LOADED=1
    -D GC9A01_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=14
    -D TFT_SCLK=10
    -D TFT_CS=8
    -D TFT_DC=4
    -D TFT_RST=6
    -D SPI_FREQUENCY=27000000
    -D USE_HSPI_PORT
monitor_speed = 115200
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  paulstoffregen/Time@^1.6.1
  claws/BH1750@^1.3.0
  jchristensen/DS3232RTC@^2.0.1
  jchristensen/Timezone@^1.2.4