#pragma once

static const char ROOT_HTML[] PROGMEM =
  "<!DOCTYPE html><html lang=en><head>"
  "<meta charset=UTF-8>"
  "<meta name=viewport content='width=device-width,initial-scale=1'>"
  "<title>WiFi Clock</title>"
  "<style>"
  "*{box-sizing:border-box;margin:0;padding:0}"
  "body{font-family:'Segoe UI',sans-serif;background:#fff;color:#222;padding:18px}"
  "h1{text-align:center;color:#c00;font-size:1.5rem;font-weight:700;letter-spacing:2px;margin-bottom:22px}"
  "h1 small{display:block;font-size:.7rem;color:#aaa;letter-spacing:4px;font-weight:400;margin-bottom:2px}"
  ".c{background:#f7f7f7;border:1px solid #e0e0e0;border-radius:10px;padding:16px 18px;margin-bottom:12px}"
  ".c h2{font-size:.72rem;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#c00;margin-bottom:12px}"
  ".fg{display:flex;gap:10px;margin-bottom:12px}"
  ".fo{flex:1;position:relative}"
  ".fo input{position:absolute;opacity:0;width:0;height:0}"
  ".fo label{display:flex;flex-direction:column;align-items:center;gap:5px;padding:14px 8px;border:2px solid #e0e0e0;border-radius:8px;cursor:pointer;background:#fff;transition:all .2s}"
  ".fo label .n{font-size:.88rem;font-weight:600;color:#444}"
  ".fo label .d{font-size:.68rem;color:#999;text-align:center}"
  ".fo input:checked+label{border-color:#f5a623;background:#fffbe6;box-shadow:0 0 0 3px rgba(245,166,35,.15)}"
  ".fo input:checked+label .n{color:#c00}"
  ".r{display:flex;align-items:center;gap:10px;margin-bottom:8px}"
  ".r label{width:64px;font-size:.78rem;color:#777;text-align:right;flex-shrink:0}"
  "input[type=number],input[type=text],input[type=password]{flex:1;background:#fff;border:1px solid #ccc;border-radius:6px;color:#222;padding:6px 10px;font-size:.88rem;outline:none;transition:border-color .2s}"
  "input[type=number]:focus,input[type=text]:focus,input[type=password]:focus{border-color:#c00}"
  "input[type=number]{width:88px;flex:none}"
  "button,input[type=submit]{width:100%;margin-top:6px;padding:9px;border:none;border-radius:8px;font-size:.88rem;font-weight:700;cursor:pointer;letter-spacing:1px;transition:background .2s}"
  "input[type=submit]{background:#c00;color:#fff}"
  "input[type=submit]:hover{background:#a00}"
  ".fw{background:#fff3cd;color:#c00;border:1px solid #f5a623}"
  ".fw:hover{background:#ffe8a0}"
  "</style></head><body>"
  "<h1><small>ESP32</small>WiFi Clock</h1>"
  "<div class=c><h2>Clock Face</h2>"
  "<form action=/clockface method=POST>"
  "<div class=fg>"
  "<div class=fo><input type=radio name=radio value=0 id=r0 %CF0%>"
  "<label for=r0><span class=n>Big Ben</span><span class=d>Classic ornate</span></label></div>"
  "<div class=fo><input type=radio name=radio value=1 id=r1 %CF1%>"
  "<label for=r1><span class=n>Mondaine</span><span class=d>Swiss SBB</span></label></div>"
  "</div><input type=submit value=Save></form></div>"
  "<div class=c><h2>Set Time (local)</h2>"
  "<form action=/settime method=POST>"
  "<div class=r><label>Year</label><input type=number name=year min=2000 max=2070 value='%YEAR%'></div>"
  "<div class=r><label>Month</label><input type=number name=month min=1 max=12 value='%MONTH%'></div>"
  "<div class=r><label>Day</label><input type=number name=day min=1 max=31 value='%DAY%'></div>"
  "<div class=r><label>Hour</label><input type=number name=hour min=0 max=23 value='%HOUR%'></div>"
  "<div class=r><label>Minute</label><input type=number name=minute min=0 max=59 value='%MINUTE%'></div>"
  "<div class=r><label>Second</label><input type=number name=second min=0 max=59 value='%SECOND%'></div>"
  "<input type=submit value=Save></form></div>"
  "<div class=c><h2>WiFi Credentials</h2>"
  "<form action=/setwificreds method=POST>"
  "<div class=r><label>SSID</label><input type=text name=wifissid value='%SSID%' placeholder='Network name'></div>"
  "<div class=r><label>Password</label><input type=password name=wifipasswd placeholder=Password></div>"
  "<input type=submit value='Save &amp; Restart'></form></div>"
  "<div class=c><h2>Ambient Light Sensor</h2>"
  "<form action=/lightsensor method=POST>"
  "<div class=r><label>Enabled</label><input type=checkbox name=enabled value=1 %LSCHK%></div>"
  "<input type=submit value=Save></form></div>"
  "<div class=c><h2>Firmware</h2>"
  "<button class=fw onclick=\"location.href='/ota'\">OTA Update&hellip;</button></div>"
  "</body></html>";

static const char OTA_HTML[] PROGMEM =
  "<!DOCTYPE html><html lang=en><head>"
  "<meta charset=UTF-8>"
  "<meta name=viewport content='width=device-width,initial-scale=1'>"
  "<title>OTA Update</title>"
  "<style>"
  "*{box-sizing:border-box;margin:0;padding:0}"
  "body{font-family:'Segoe UI',sans-serif;background:#fff;color:#222;padding:18px}"
  "h1{text-align:center;color:#c00;font-size:1.5rem;font-weight:700;letter-spacing:2px;margin-bottom:22px}"
  "h1 small{display:block;font-size:.7rem;color:#aaa;letter-spacing:4px;font-weight:400;margin-bottom:2px}"
  ".c{background:#f7f7f7;border:1px solid #e0e0e0;border-radius:10px;padding:16px 18px;margin-bottom:12px}"
  ".c h2{font-size:.72rem;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#c00;margin-bottom:12px}"
  "input[type=file]{display:none}"
  ".pick{display:flex;align-items:center;gap:10px;margin-bottom:10px}"
  ".pick label{padding:7px 14px;border:2px solid #f5a623;border-radius:7px;background:#fffbe6;color:#c00;font-size:.82rem;font-weight:700;cursor:pointer;white-space:nowrap;transition:background .2s}"
  ".pick label:hover{background:#ffe8a0}"
  ".pick span{font-size:.82rem;color:#888;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
  "button{width:100%;padding:11px;border:2px solid #c00;border-radius:8px;font-size:.9rem;font-weight:700;cursor:pointer;background:#fff;color:#c00;letter-spacing:1px;transition:all .2s}"
  "button:hover{background:#c00;color:#fff}"
  ".pw{background:#e8e8e8;border-radius:4px;height:14px;overflow:hidden;margin:10px 0 4px}"
  ".pb{height:100%;width:0%;background:#c00;transition:width .3s}"
  "#st{text-align:center;color:#777;font-size:.82rem;margin-top:4px}"
  ".sp{width:38px;height:38px;border:4px solid #e0e0e0;border-top-color:#c00;border-radius:50%;animation:s 1s linear infinite;margin:10px auto}"
  "@keyframes s{to{transform:rotate(360deg)}}"
  "a{display:block;text-align:center;color:#c00;margin-top:12px;font-size:.88rem}"
  "</style></head><body>"
  "<h1><small>ESP32</small>OTA Update</h1>"
  "<div class=c><h2>Upload Firmware</h2>"
  "<div id=ua>"
  "<div class=pick>"
  "<input type=file id=fw accept=.bin onchange=\"document.getElementById('fn').textContent=this.files[0]?this.files[0].name:'No file chosen'\">"
  "<label for=fw>&#128194; Choose&hellip;</label>"
  "<span id=fn>No file chosen</span>"
  "</div>"
  "<button onclick=up()>&#8679; Upload &amp; Install</button>"
  "</div>"
  "<div id=pa style=display:none>"
  "<div class=sp id=sp></div>"
  "<div class=pw><div class=pb id=pb></div></div>"
  "<p id=st>Uploading&hellip;</p>"
  "</div></div>"
  "<a href=/>&#8592; Back</a>"
  "<script>"
  "function up(){"
  "var f=document.getElementById('fw').files[0];"
  "if(!f){alert('Select a .bin file');return;}"
  "document.getElementById('ua').style.display='none';"
  "document.getElementById('pa').style.display='block';"
  "var x=new XMLHttpRequest();"
  "x.upload.onprogress=function(e){"
  "if(e.lengthComputable){"
  "var p=Math.round(e.loaded/e.total*100);"
  "document.getElementById('pb').style.width=p+'%';"
  "document.getElementById('st').textContent='Uploading '+p+'%';}};"
  "x.onload=function(){"
  "document.getElementById('sp').style.display='none';"
  "document.getElementById('pb').style.width='100%';"
  "document.getElementById('st').textContent='Done! Restarting in 5s';"
  "setTimeout(function(){location.href='/';},5000);};"
  "x.onerror=function(){document.getElementById('st').textContent='Failed!';};"
  "var fd=new FormData();"
  "fd.append('update',f,f.name);"
  "x.open('POST','/update');"
  "x.send(fd);}"
  "</script></body></html>";

static const char RESTART_HTML[] PROGMEM =
  "<!DOCTYPE html><html lang=en><head>"
  "<meta charset=UTF-8>"
  "<meta name=viewport content='width=device-width,initial-scale=1'>"
  "<title>Restarting</title>"
  "<style>"
  "*{box-sizing:border-box;margin:0;padding:0}"
  "body{font-family:'Segoe UI',sans-serif;background:#fff;color:#222;padding:18px}"
  "h1{text-align:center;color:#c00;font-size:1.5rem;font-weight:700;letter-spacing:2px;margin-bottom:22px}"
  "h1 small{display:block;font-size:.7rem;color:#aaa;letter-spacing:4px;font-weight:400;margin-bottom:2px}"
  ".c{background:#f7f7f7;border:1px solid #e0e0e0;border-radius:10px;padding:24px 18px;text-align:center}"
  ".sp{width:44px;height:44px;border:4px solid #e0e0e0;border-top-color:#c00;border-radius:50%;animation:s 1s linear infinite;margin:0 auto 14px}"
  "@keyframes s{to{transform:rotate(360deg)}}"
  ".m{color:#c00;font-size:1.05rem;font-weight:700;margin-bottom:6px}"
  ".s{color:#888;font-size:.83rem;margin-bottom:10px}"
  ".cd{color:#bbb;font-size:.78rem}"
  ".cd b{color:#c00}"
  "</style></head><body>"
  "<h1><small>ESP32</small>WiFi Clock</h1>"
  "<div class=c>"
  "<div class=sp></div>"
  "<p class=m>Saved!</p>"
  "<p class=s>Device is restarting&hellip;</p>"
  "<p class=cd>Returning home in <b id=c>6</b>s</p>"
  "</div>"
  "<script>"
  "var s=6,i=setInterval(function(){"
  "s--;document.getElementById('c').textContent=s;"
  "if(s<=0){clearInterval(i);location.href='/';}"
  "},1000);"
  "</script></body></html>";
